### ISSUE TITLE
The ChatGPT relay server?

### ISSUE THREAD

**Issue by godfg111** [trzy/ChatARKit#2]
When I implemented the ChatGPT relay server, there was a problem that I couldn't solve.
`Traceback (most recent call last):
  File "D:\Anaconda3\envs\PyTorch\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\PyTorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\ChatARKit\ChatARKit-master\chatgpt.py", line 183, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "D:\Anaconda3\envs\PyTorch\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "F:\ChatARKit\ChatARKit-master\chatgpt.py", line 43, in run
    prompt, callback = await self._prompt_queue.get()
  File "D:\Anaconda3\envs\PyTorch\lib\asyncio\queues.py", line 159, in get
    await getter
RuntimeError: Task <Task pending coro=<ChatGPTTask.run() running at F:\ChatARKit\ChatARKit-master\chatgpt.py:43> cb=[gather.<locals>._done_callback() at D:\Anaconda3\envs\PyTorch\lib\asyn
cio\tasks.py:691]> got Future <Future pending> attached to a different loop
Task was destroyed but it is pending!
task: <Task pending coro=<ServerTask.run() running at F:\ChatARKit\ChatARKit-master\chatgpt.py:117> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x0000027A8A701
078>()]> cb=[gather.<locals>._done_callback() at D:\Anaconda3\envs\PyTorch\lib\asyncio\tasks.py:691]>`

**Comment by trzy** [comment]
Does this happen when you try to kill the process via Ctrl-C?

I have not tested the relay server in over a month and it may be otherwise broken. I’ve been planning to update the app to connect directly to the ChatGPT service using login credentials for the paid service. Hopefully in the next couple weeks I’ll find some time.

**Comment by trzy** [comment]
I've pushed an update that removes the relay server altogether. The iOS app now communicates directly with ChatGPT. Just make sure to enter your API keys into APIKey.swift and build.
