### ISSUE TITLE
 Chromium window fail to appear

### ISSUE THREAD

**Issue by LI-U-ZY** [trzy/ChatARKit#3]
After I completed the previous four steps, paste and press session token obtained in step 2,the Chromium window didn't show up，please help me.
--"By default, it will listen on port 6502. It will ask you for the session token obtained in step 2. Paste it and press enter. A Chromium window should appear and automatically log into ChatGPT"

**Comment by trzy** [comment]
I just fired it up and while it did pop up the browser, it crashed. Looks like pyChatGPT hasn't been updated in months and OpenAI has changed the web site layout, breaking compatibility.

What I'd like to do this week or next is find some time to look into the official ChatGPT API. If I can get that plugged in, I could eliminate the need for any sort of relay server and everything could be run directly from the iOS app. 

Stay tuned and check back in 1 and 2 weeks.
